#!/bin/sh
# $Id: mk,v 1.3 2020-01-31 16:33:26-08 - - $
cid $0 *.c testfile.in
mkc *.c
binarydump testfile.in >testbinary.out 2>&1
hexadecimaldump testfile.in >testhexadecimal.out 2>&1
mkpspdf Listing.src.ps *.c
mkpspdf -N Listing.out.ps *.out
zcat /usr/share/man/man1/xxd.1.gz | groff -man -spte -Tps >xxd.1.ps
ps2pdf xxd.1.ps
